### PR TITLE
Compile to exe

### PR DESCRIPTION
**Pull request by mfbehrens99**
+ Fixed utf-8 bug in setup.py line 3-4
+ Import and specify `build_py`
+ Added entry point for scripts

Issue #154

### CODE REVIEW

**Comment by matze-dd** [comment]
Thank you for this! :)

Unfortunately, I'm not really familiar with build\_py. So, my question is: will your change to setup.py lead to a (possibly unwanted) compilation, if I use that for uploading to PyPI and one installs YaLafi with pip from PyPI?

**Comment by mfbehrens99** [comment]
Okay, this feature doesn't change or removes anything. It just tells pip to put a file called YaLafi to the Scripts folder (`C:\Users\USERNAME\AppData\Roaming\Python\Python39\Scripts`) so you can run YaLafi from the console using the command `yalafi` without any `python -m yalafi.shell`. But if you don't want the change I can also just run the python command. I just thought it might be useful.

Best
Michael

**Comment by matze-dd** [comment]
> ... so you can run YaLafi from the console using the command yalafi without any python -m yalafi.shell. But if you don't want the change I can also just run the python command. I just thought it might be useful.

To be honest, I would prefer to keep things as they are. I'd close this PR and issue #154 if this is OK for you.

Thank you nevertheless for the effort!

**Comment by mfbehrens99** [comment]
Yes that's no problem

**Pull request closed without merging**
