### PR TITLE
mention simpler language tool Vim plugin

### PR DESCRIPTION
**Pull request by Konfekt**
disclaimer: I am the plugin's author

### CODE REVIEW

**Comment by matze-dd** [comment]
Thanks a lot for this!

Your `errorformat` is more comprehensive then mine in [ltyc.vim](https://github.com/matze-dd/YaLafi/blob/master/ltyc.vim). One difference is that you pick up the file name from line "Working on ...". Did you test that this will work with the LaTeX filter output , too?

Some minor remarks on the README:
- Is the heading "### Application of plugin vim-LanguageTool" correct?
- We should give a direct hint like, for instance: Add `output=plain` to `yalafi-grammarous`.
- The map to `:LanguageToolCheck` now should be to `:make` or `:lmake`?

**Comment by Konfekt** [comment]
Thank you for your kind reply. My latest commit applies your suggestions.

On looking at [ltyc.vim](https://github.com/matze-dd/YaLafi/blob/master/ltyc.vim) I realize that `YaLaFi` already santizes the output in a Vim that the involved error format of `vim-langtool` is no longer needed. Therefore, these instructions seem unnecessary, though it might still be good to know that there is a Vim compiler file that directly works on the output of LanguageTool itself.

By reading about the other Vim plug-ins for LanguageTool, I got the impression that the output format of LanguageTool is kept, but only the line and column numbers are adapted back and forth to the plain input text converted from the TeX source.

**Comment by matze-dd** [comment]
> My latest commit applies your suggestions.

Thanks!

> ... though it might still be good to know that there is a Vim compiler file that directly works on the output of LanguageTool itself.

Yes, we agree. It would be nice to describe all relevant Vim plugins, so that a possible user can choose the most suitable one.

> By reading about the other Vim plug-ins for LanguageTool, I got the impression that the output format of LanguageTool is kept, but only the line and column numbers are adapted back and forth to the plain input text converted from the TeX source.

This is correct, but unfortunately not the full truth. For instance, if yalafi.shell is not running LanguageTool in server mode (option `--server no`), then LanguageTool receives the plain text via stdin. Consequently, one cannot pick the file name from its message line `Working on ...`. Instead, yalafi.shell precedes each single message with a line `=== <file_name> ===`, which is evaluated by errorformat in ltyc.vim. (In fact, yalafi.shell reads LanguageTool's output in JSON format and mimics its text output format on `--output plain`. In mode `--server my`, the HTML reply is translated to this format. In both cases, no new line `Working on ...` is generated.)

**Comment by Konfekt** [comment]
> This is correct, but unfortunately not the full truth. For instance, if yalafi.shell is not running LanguageTool in server mode (option --server no), then LanguageTool receives the plain text via stdin. Consequently, one cannot pick the file name from its message line Working on .... Instead, yalafi.shell precedes each single message with a line === <file_name> ===, which is evaluated by errorformat in ltyc.vim. (In fact, yalafi.shell reads LanguageTool's output in JSON format and mimics its text output format on --output plain. In mode --server my, the HTML reply is translated to this format. In both cases, no new line Working on ... is generated.)

Yes, on looking at [ltyc.vim](https://github.com/matze-dd/YaLafi/blob/master/ltyc.vim) I realize that `YaLaFi` already santizes the output in a Vim that the involved error format of `vim-langtool` is no longer needed. 

This is, `ltyc.vim` seems to achieve for the saner output of `yalafi` (each error contains the file name) what `langtool.vim` achieves for the less standard output of `LanguageTool`.

**Comment by matze-dd** [comment]
> This is, ltyc.vim seems to achieve for the saner output of yalafi (each error contains the file name) what langtool.vim achieves for the less standard output of LanguageTool.

So, do you think that your plugin `vim-langtool` can offer additional functionality compared to the version described in [\[this section\]](https://github.com/matze-dd/YaLafi#application-via-compiler-interface)? If yes, could you test whether the `errorformat` in langtool.vim really works with the shell script yalafi-grammarous?

**Comment by Konfekt** [comment]
No, I don't think so.  I wrote the plug-in because I preferred a quickfix list instead of the custom buffers via the XML output that both other plug-ins offer. There is no additional functionality.

As a side note, you could mention for `ytlc.vim` the async functionality via an additional plug-in as in https://github.com/Konfekt/vim-langtool#usage .

**Comment by matze-dd** [comment]
> As a side note, you could mention for ytlc.vim the async functionality via an additional plug-in as in https://github.com/Konfekt/vim-langtool#usage .

Thank you for this hint. Before, I will have to test that.

I hope that it is OK, if I close this PR.

**Pull request closed without merging**
